# Generated by Django 3.0 on 2021-05-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_orgdetails_no_of_childrens'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='Andra Pradesh', max_length=10),
        ),
    ]
