# Generated by Django 3.0 on 2021-04-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210430_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[('D', 'Donor'), ('O', 'Organisation'), ('G', 'Guest')], default='G'),
        ),
    ]
