# Generated by Django 3.0 on 2021-05-04 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20210430_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('ways_to_donate', models.CharField(choices=[('1', 'Yearly Once'), ('2', 'Monthly Once'), ('3', 'Quarterly Once')], max_length=50)),
                ('donating_to', models.CharField(max_length=50)),
                ('sponsor_way', models.CharField(choices=[('F', 'Food'), ('C', 'Clothes'), ('M', 'Money')], max_length=50)),
                ('donating_date', models.DateField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
