# Generated by Django 3.0 on 2021-05-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20210504_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='ways_to_donate',
            field=models.CharField(choices=[('1', 'Yearly Once'), ('2', 'Monthly Once'), ('3', 'Quarterly Once'), ('4', 'One time donation')], max_length=50),
        ),
    ]
