# Generated by Django 3.0 on 2021-05-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20210504_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='sponsor_way',
            field=models.CharField(choices=[('Food', 'Food'), ('Clothes', 'Clothes'), ('Money', 'Money')], max_length=50),
        ),
        migrations.AlterField(
            model_name='donate',
            name='ways_to_donate',
            field=models.CharField(choices=[('Yearly', 'Yearly Once'), ('Monthly', 'Monthly Once'), ('Quarterly', 'Quarterly Once'), ('One Time', 'One time donation')], max_length=50),
        ),
    ]
